#pragma once

#include <QAction>
#include <QApplication>
#include <QByteArray>
#include <QCloseEvent>
#include <QColor>
#include <QComboBox>
#include <QDialog>
#include <QDir>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFont>
#include <QFontDatabase>
#include <QFontMetrics>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHash>
#include <QHBoxLayout>
#include <QKeySequence>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QMainWindow>
#include <QMenu>
#include <QMessageBox>
#include <QMouseEvent>
#include <QPaintEvent>
#include <QPainter>
#include <QPalette>
#include <QPoint>
#include <QPolygon>
#include <QPointer>
#include <QPushButton>
#include <QRadioButton>
#include <QRect>
#include <QResizeEvent>
#include <QRubberBand>
#include <QSaveFile>
#include <QScrollArea>
#include <QSignalBlocker>
#include <QShortcut>
#include <QSet>
#include <QSizePolicy>
#include <QStyleFactory>
#include <QString>
#include <QStringList>
#include <QTextStream>
#include <QTimer>
#include <QVBoxLayout>
#include <QVector>
#include <QWidget>

#include <algorithm>
#include <cmath>
#include <array>
#include <functional>
#include <limits>
#include <memory>
#include <utility>
#include <vector>

#include "adl_parser.h"
#include "adl_writer.h"
#include "arc_element.h"
#include "cartesian_plot_element.h"
#include "byte_monitor_element.h"
#include "bar_monitor_element.h"
#include "slider_element.h"
#include "wheel_switch_element.h"
#include "scale_monitor_element.h"
#include "display_properties.h"
#include "display_state.h"
#include "image_element.h"
#include "meter_element.h"
#include "line_element.h"
#include "medm_colors.h"
#include "oval_element.h"
#include "strip_chart_element.h"
#include "polygon_element.h"
#include "polyline_element.h"
#include "rectangle_element.h"
#include "composite_element.h"
#include "resource_palette_dialog.h"
#include "text_element.h"
#include "choice_button_element.h"
#include "menu_element.h"
#include "message_button_element.h"
#include "shell_command_element.h"
#include "related_display_element.h"
#include "text_entry_element.h"
#include "text_monitor_element.h"

#include "display_window_impl.h"
